Blows up on tbe build with:
CssSyntaxError: tailwindcss: /home/runner/work/thruk-custom-theme/thruk-custom-theme/src/themes/Codeweavers/src/theme.css:38:1: You cannot `@apply` the `flex` utility here because it creates a circular dependency.